<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Binary, Decimal, Hex</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="binary-decimal-hex_files/libs/clipboard/clipboard.min.js"></script>
<script src="binary-decimal-hex_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="binary-decimal-hex_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="binary-decimal-hex_files/libs/quarto-html/popper.min.js"></script>
<script src="binary-decimal-hex_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="binary-decimal-hex_files/libs/quarto-html/anchor.min.js"></script>
<link href="binary-decimal-hex_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="binary-decimal-hex_files/libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="binary-decimal-hex_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="binary-decimal-hex_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="binary-decimal-hex_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Binary, Decimal, Hex</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>(bin-dec-hex)= ## Learning Outcomes</p>
<ul>
<li>Translate between binary, decimal, and hexadecimal number representations</li>
<li>Use hexadecimal as shorthand for binary</li>
<li>Know when each representation is useful</li>
</ul>
<p>::::{note} 🎥 Lecture Video :class: dropdown</p>
<p>:::{iframe} https://www.youtube.com/embed/5rmB4SvfDPo?si=7YF8BXMnDpFCQiCH :width: 100% :title: “[CS61C FA20] Lecture 02.2 - Number Representation: Conversions” :::</p>
<p>::::</p>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>In this section, we discuss how computer architects and computer scientists translate between the rich world that humans see and information that computers store. The former is framed by how humans think—after all, we have ten fingers, also known as “digits”. The latter is in bits.</p>
</section>
<section id="numerals-as-a-representation-of-numbers" class="level2">
<h2 class="anchored" data-anchor-id="numerals-as-a-representation-of-numbers">Numerals as a representation of Numbers</h2>
<p>Let’s discuss the idea of formally representing a <strong>number</strong> with many possible <strong>numerals</strong>, i.e., symbols.</p>
<ul>
<li><strong>Numeral</strong>: A symbol (or series of symbols) or name that stands for a number, e.g., 4 , four , quatro , IV , IIII , …. Numerals are composed of multiple symbols called <strong>digits</strong>.</li>
<li><strong>Number</strong>: The “idea” in our minds, e.g., the concept of “4”. There is only ONE concept of a number, but there can be many possible numeric representations via many possible numerals.</li>
</ul>
<p>:::{figure} images/numeral-number.png :label: fig-numeral-number :alt: “A diagram features a horizontal gold abstraction line separating the word Numeral at the top from the word Number at the bottom. This visual layout reinforces the caption by positioning numerals as the symbolic representations above the line and numbers as the underlying abstract concepts below it.” :align: center</p>
<p>Numerals (and therefore digits) are representations of numbers. :::</p>
<p><strong>?@fig-every-base-is-base-10</strong> is a motivating (and humorous) example. An alien and an astronaut are discussing how to represent the number of rocks in a pile.</p>
<p>:::{figure} images/every-base-is-base-10.png :label: fig-every-base-is-base-10 :alt: “A astronaut talking to an alien with 2 fingers per hand and there are 4 rocks on the ground. Alien says ‘There are 10 rocks.’ Astronaut says ‘Oh, you must be using base 4. See, I use base 10.’ Alien says ‘No.&nbsp;I use base 10. What is base 4?’ Caption reads ‘Every base is base 10’” :align: center</p>
<p>Every base is base 10 (<a href="https://web.archive.org/web/20160505151914/http://cowbirdsinlove.com/43">web.archive.org</a>) :::</p>
<p>The alien, the astronaut, and the pile of rocks use three different representations of the number <em>four</em>. The astronaut uses the numeral 4 to represent four as a base-10 integer. The alien uses the numeral 10 to represent four as a base-4 integer. The pile of rocks uses four rocks to represent four as, well, a pile of rocks.</p>
</section>
<section id="binary-decimal-and-hexadecimal-representations" class="level2">
<h2 class="anchored" data-anchor-id="binary-decimal-and-hexadecimal-representations">Binary, Decimal, and Hexadecimal Representations</h2>
<p>While there are an infinite number of bases with which to represent numbers, we discuss three will be the most useful to us, as computer scientists: <strong>decimal</strong>, <strong>binary</strong>, and <strong>hexadecimal</strong> representations.</p>
<p><strong>?@tbl-dec-hex-bin</strong> probably makes little sense to you at the moment, but we present it first so you can make some educated guesses.</p>
<p>:::{table} Decimal, binary, and hexadecimal digits. :label: tbl-dec-hex-bin :align: center</p>
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 27%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">System</th>
<th style="text-align: center;"># Digits</th>
<th style="text-align: left;">Digits</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Decimal</td>
<td style="text-align: center;">10</td>
<td style="text-align: left;"><code>0, 1, 2, 3, 4, 5, 6, 7, 8, 9</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">Binary</td>
<td style="text-align: center;">2</td>
<td style="text-align: left;"><code>0, 1</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hexadecimal</td>
<td style="text-align: center;">16</td>
<td style="text-align: left;"><code>0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A,  B,  C,  D,  E,  F</code></td>
</tr>
</tbody>
</table>
<p>:::</p>
<section id="decimal-base-10-ten-numbers" class="level3">
<h3 class="anchored" data-anchor-id="decimal-base-10-ten-numbers">Decimal: Base 10 (Ten) Numbers</h3>
<p>First, consider <strong>decimal</strong> numerals. The decimal numeral <span class="math inline">\(3271\)</span> is written in that order, because it describes how to count powers of <strong>ten</strong> corresponding to the equation below (note the superscript <span class="math inline">\(10\)</span> denotes a base-10 numeral):</p>
<p><span class="math display">\[
\begin{align}
3271
&amp;= 3271_{10} \\
&amp;=  (3 \times 10^3) + (2 \times 10^2) + (7 \times 10^1) + (1 \times 10^0)
\end{align}
\]</span></p>
<p>Each of the four digits specify a <em>count</em> of a power of ten. We add these up to get the number three thousand, two hundred seventy-one.</p>
<p>:::{note} Explanation :class: dropdown</p>
<ul>
<li>The <strong>rightmost</strong> digit, <em>1</em>, corresponds to the <strong>smallest</strong> power of 10 that composes a non-negative integer. This is the zero-th power, or <span class="math inline">\(10^0 = 1\)</span>. We include <em>one</em>.</li>
<li>The next digit, <span class="math inline">\(7\)</span>, corresponds to the next smallest power of 10, which is <span class="math inline">\(10^1 = 10\)</span>, or ten. We include <em>seven</em> tens.</li>
<li>The next digit, <span class="math inline">\(2\)</span>, corresponds to the next smallest power of 10, which is <span class="math inline">\(10^2 = 100\)</span>, or one hundred. We include <em>two</em> hundreds.</li>
<li>The final <strong>leftmost</strong> digit, corresponds to the <strong>largest</strong> power of 10 for this number, which is <span class="math inline">\(10^3 = 1000\)</span>, or one thousand. We include <em>three</em> thousands. :::</li>
</ul>
<p>This process will seem natural to you—because we humans think in base ten—but we will see that we can apply this understanding to represent numbers in other bases. Nevertheless, we highlight a few implicit assumptions:</p>
<ul>
<li>For now, we only consider powers of 10 needed to compose non-negative integers; we will discuss how to represent fractions later. The smallest such power of 10 is <span class="math inline">\(10^0 = 1\)</span>.</li>
<li>The “largest” power of 10 for this number can be more precisely defined as the largest power of 10 corresponding to a non-zero digit. In other words, the decimal <span class="math inline">\(0 \dots 03271\)</span> with leading zeros (on the left) and the decimal <span class="math inline">\(3271\)</span> represent the same number.</li>
<li>Base ten uses the ten digits <code>0</code> to <code>9</code> to create unique decimal representations. In other words, to form the decimal <span class="math inline">\(10\)</span>, instead of using ten of <span class="math inline">\(10^0\)</span>, we use one <span class="math inline">\(10^1\)</span> and zero <span class="math inline">\(10^0\)</span>. <a href="https://en.wikipedia.org/wiki/Radix">Wikipedia</a> provides a more formal discussion of uniqueness.</li>
</ul>
</section>
<section id="base-2-two-numbers-binary" class="level3">
<h3 class="anchored" data-anchor-id="base-2-two-numbers-binary">Base 2 (Two) Numbers, Binary</h3>
<p>Binary numbers like <code>1101</code> are written in that order to describe how to count powers of <strong>two</strong>. Notably, the two <strong>bi</strong>nary digi<strong>ts</strong>, <code>0</code> and <code>1</code>, are the namesake of the <strong>b</strong>it (which takes on those two values).</p>
<blockquote class="blockquote">
<p>What does the binary numeral <code>1101</code> represent?</p>
</blockquote>
<p>Because humans think in decimal, we convert this binary value to decimal with a similar process as above:</p>
<p><span class="math display">\[
\begin{align}
\texttt{0b1101}
&amp;= 1101_{2} \\
&amp;= (1 \times 2^3) + (1 \times 2^2) + (0 \times 2^1) + (1 \times 2^0) \\
&amp;=  8         +  4        +  0         +  1 \\
&amp;=  13
\end{align}
\]</span></p>
<p>:::{note} Explanation :class: dropdown</p>
<ul>
<li>The <strong>rightmost</strong> digit, <em>1</em>, corresponds to the <strong>smallest</strong> power of <strong>2</strong> that composes a non-negative integer. This is <em>still</em> the zero-th power, or <span class="math inline">\(2^0 = 1\)</span>. We include <em>one</em> one.</li>
<li>The next digit, <em>0</em>, corresponds to <span class="math inline">\(2^1 = 2\)</span>, or two. We include <em>zero</em> twos.</li>
<li>The next digit, <em>1</em>, corresponds to <span class="math inline">\(2^2 = 4\)</span>, or four. We include <em>one</em> four.</li>
<li>The final <strong>leftmost</strong> digit, <em>1</em> corresponds to <span class="math inline">\(2^3 = 8\)</span>, or eight. We include <em>one</em> eight.</li>
</ul>
<p>Adding up one one, zero twos, one four, and one eight gives thirteen, or the decimal <span class="math inline">\(13\)</span>. :::</p>
<p>Other notes:</p>
<ul>
<li>We prepend the prefix <code>0b</code> to denote that the numeral <code>1101</code> should be interpreted in base 2; the <strong>shorthand</strong> <code>0b1101</code> is equivalent to the mathematical notation <span class="math inline">\(1101_2\)</span> but can be written with a standard keyboard.</li>
<li>Like before, <code>0b0...01101</code> and <code>0b1101</code> represent the same nunber, thirteen.</li>
<li>Because there are just two binary digits <code>0</code> and <code>1</code>, in binary we are always either including a value (here, a specific power of two), or not including it. <code>1</code> or <code>0</code>, <code>True</code> or <code>False</code>. This idea of binary representing “inclusion” or “exclusion” will show up repeatedly in this course.</li>
</ul>
</section>
<section id="base-16-sixteen-s-hexadecimal" class="level3">
<h3 class="anchored" data-anchor-id="base-16-sixteen-s-hexadecimal">Base 16 (Sixteen) #s, Hexadecimal</h3>
<p>Finally, we consider hexadecimal numbers.</p>
<blockquote class="blockquote">
<p>What does the hexadecimal numeral <code>A5</code> represent?</p>
</blockquote>
<p>Convert to decimal:</p>
<p><span class="math display">\[
\begin{align}
\texttt{0xA5}
&amp;= A5_{16} \\
&amp; = (10 \times 16^1) + (5 \times 16^0) \\
&amp; =  160        +  5 \\
&amp; =  165
\end{align}
\]</span></p>
<p>We prepend the prefix <code>0x</code> to denote that the numeral <code>A5</code> should be interpreted in base 16. Like before, the shorthand <code>0xA5</code> is equivalent to <span class="math inline">\(A5_{16}\)</span> but can be written with a standard keyboard.</p>
<p>Hexadecimal digits are useful as shorthand for representing groups of four binary digits. We discuss more <a href="#which-base">at the end of this section</a>.</p>
</section>
</section>
<section id="convert-between-representations" class="level2">
<h2 class="anchored" data-anchor-id="convert-between-representations">Convert between representations</h2>
<div class="{tip}">
<p>Memorize <strong>?@tbl-dec-hex-bin-16</strong>. As you will soon see, it will be useful to quickly convert between decimal, binary, and hexadecimal representations.</p>
</div>
<p>:::{table} First sixteen numbers as decimal, hexadecimal, and binary representations. :label: tbl-dec-hex-bin-16 :align: center</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Number</th>
<th style="text-align: left;">Hexadecimal</th>
<th style="text-align: left;">Binary</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: left;"><code>0</code></td>
<td style="text-align: left;"><code>0000</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;"><code>1</code></td>
<td style="text-align: left;"><code>0001</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;"><code>2</code></td>
<td style="text-align: left;"><code>0010</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;"><code>3</code></td>
<td style="text-align: left;"><code>0011</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;"><code>4</code></td>
<td style="text-align: left;"><code>0100</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: left;"><code>5</code></td>
<td style="text-align: left;"><code>0101</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;"><code>6</code></td>
<td style="text-align: left;"><code>0110</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: left;"><code>7</code></td>
<td style="text-align: left;"><code>0111</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">8</td>
<td style="text-align: left;"><code>8</code></td>
<td style="text-align: left;"><code>1000</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">9</td>
<td style="text-align: left;"><code>9</code></td>
<td style="text-align: left;"><code>1001</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: left;"><code>A</code></td>
<td style="text-align: left;"><code>1010</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">11</td>
<td style="text-align: left;"><code>B</code></td>
<td style="text-align: left;"><code>1011</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">12</td>
<td style="text-align: left;"><code>C</code></td>
<td style="text-align: left;"><code>1100</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">13</td>
<td style="text-align: left;"><code>D</code></td>
<td style="text-align: left;"><code>1101</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">14</td>
<td style="text-align: left;"><code>E</code></td>
<td style="text-align: left;"><code>1110</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">15</td>
<td style="text-align: left;"><code>F</code></td>
<td style="text-align: left;"><code>1111</code></td>
</tr>
</tbody>
</table>
<p>:::</p>
<p>Let’s discuss conversion in more detail. We only consider “unsigned” numerals, i.e., non-negative numbers.</p>
<p>If we have an <span class="math inline">\(n\)</span>-digit unsigned numeral <span class="math inline">\(d_{n-1}\)</span> <span class="math inline">\(d_{n-2}\)</span>…<span class="math inline">\(d_0\)</span> in radix (or base) <span class="math inline">\(r\)</span>, then the value of that numeral is</p>
<p>(eq-unsigned-rep)= <span class="math display">\[
\sum_{i=0}^{n-1} r^i d_i,
\]</span></p>
<p>which is just fancy notation to say that instead of a 10’s or 100’s place we have an <span class="math inline">\(r\)</span>’s or <span class="math inline">\(r^2\)</span>’s place. For the three radices binary, decimal, and hex, we just let <span class="math inline">\(r\)</span> be 2, 10, and 16, respectively.</p>
<section id="decimal-rightarrow-binary" class="level3">
<h3 class="anchored" data-anchor-id="decimal-rightarrow-binary">Decimal <span class="math inline">\(\rightarrow\)</span> Binary</h3>
<p>The slidedeck below shows how we can convert the decimal <span class="math inline">\(13\)</span> into its binary representation, <code>0b1101</code>.</p>


<title>
Animation that steps through the enumerated text in this section. Access &lt;a href="https://docs.google.com/presentation/d/1aihcZDiAEMCarSs-QIzRE_ixW5mACYYTykdmRyqIZUc/edit?usp=sharing"&gt;original Google Slides&lt;/a&gt;
</title>

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSRRi1DDwigsxmr5R_fPwZ1uAOKKJ-fblPQg6GFNICf9he20UUYX_gZLwdrMG4HRvrtcD3e9nkBwk29/pubembed?start=false&amp;loop=false" frameborder="0" width="480" height="400" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true">
</iframe>
<br>

<p>Let <code>val</code> be <span class="math inline">\(13\)</span> in the explanation below. Click to show.</p>
<p>:::{note} Explanation :class: dropdown</p>
<p>Make columns 1, 2, 4, 8, which correspond to increasing integer powers of two. These columns also correspond to a 4-digit binary number, e.g., <code>0b _ _ _ _</code>.</p>
<ol type="1">
<li>Take the largest power of two: <span class="math inline">\(2^3 = 8\)</span>, or eight. This “fits” into <code>val</code>, so “use” it. “Using” means we need the binary digit <code>1</code>. Set the 4th-from-the-right space to <code>1</code>, i.e., populate <code>0b 1 _ _ _</code>. Because we have now “used up” eight, subtract it and update <code>val</code> to 5. This is the remainder we have to represent.</li>
<li>Take the next power of two: <span class="math inline">\(2^2 = 4\)</span>, or four. “Use” it by setting the 3rd-from-the-right space to <code>1</code>, i.e., populate <code>0b 1 1 _ _</code>. Update <code>val</code> to 1.</li>
<li>Take the next power of two: <span class="math inline">\(2^1 = 2\)</span>, or two. We cannot “use” it because it is too big. “Not using” means we need the binary digit <code>0</code>. Set the second-from-the-right space to <code>0</code>, i.e., populate <code>0b 1 1 0 _</code>. <code>bal</code> is unchanged and is still 1.</li>
<li>Take the next power of two, which is also the smallest: <span class="math inline">\(2^0 = 1\)</span>, or one. “Use” it by setting the rightmost space to <code>1</code>, i.e., populate <code>0b 1 1 0 1</code>. Update <code>val</code> to 0.</li>
</ol>
<p>The resulting <strong>binary string</strong> is <code>0b1101</code>. By yourself, practice going the other way and check that <code>0b1101</code> represents the decimal number <span class="math inline">\(13\)</span>.</p>
<p>:::</p>
<p>The process above relies on a few colloquial observations:</p>
<ul>
<li>The largest power of two we could possibly need is less than the number <code>val</code> itself.</li>
<li>The smallest power of two we could possibly need is always the zero-th power, i.e., <span class="math inline">\(2^0 = 1\)</span>.</li>
<li>Start with larger power of twos first. Otherwise you may run into scenarios where you count beyond the number of digits available (here, only <code>0</code> and <code>1</code>).</li>
</ul>
<p>Here is one attempt at describing the algorithm to convert a number <code>val</code> into its binary representation:</p>
<ul>
<li>Make a set of columns, one for each power of two. This corresponds to your <span class="math inline">\(n\)</span>-digit binary number, e.g., <code>0b _ _ ... _ _</code>, with <span class="math inline">\(n\)</span> blanks.</li>
<li>Start from the leftmost column and go right (i.e., for <span class="math inline">\(i\)</span> from <span class="math inline">\(n-1\)</span> to <span class="math inline">\(0\)</span>, inclusive):
<ul>
<li>For the current column <span class="math inline">\(i\)</span>, corresponding to <span class="math inline">\(2^i\)</span>:
<ul>
<li>Is the current column less than or equal to <code>val</code>?
<ul>
<li>If yes, count how many <span class="math inline">\(2^i\)</span> fit into <code>val</code>. For base 2, the count is <code>1</code>, so subtract <span class="math inline">\(1 \times 2^i\)</span> from <code>val</code>. Keep going.</li>
<li>If no, put <code>0</code> and keep going.</li>
</ul></li>
</ul></li>
</ul></li>
<li>Stop this process once <code>val</code> hits zero.</li>
</ul>
<p>The point of this example is to teach you some tricks for converting between bases. Some students find the algorithmic description above more understandable than the mathematical description in <strong>?@eq-unsigned-rep</strong>. If the latter makes more sense to you, then go for it.</p>
</section>
<section id="decimal-rightarrow-hexadecimal" class="level3">
<h3 class="anchored" data-anchor-id="decimal-rightarrow-hexadecimal">Decimal <span class="math inline">\(\rightarrow\)</span> Hexadecimal</h3>
<p>The slidedeck below converts <span class="math inline">\(165\)</span> into its hexadecimal representation, <code>0xA5</code>.</p>


<title>
Animation that steps through the enumerated text in this section. Access &lt;a href="https://docs.google.com/presentation/d/1rHScPLQLom3OzhZyGzhct8vpXtO-AWRiXyr5C-9Qszs/edit?usp=sharing"&gt;original Google Slides&lt;/a&gt;
</title>

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTWgqxt2kl5ip7bRfRY7P81WiQGDJSrAuKmkqE1m3mnrerVBeN2s9PGJVVaIQu0aDlsNfuvcRCK09q9/pubembed?start=false&amp;loop=false" frameborder="0" width="480" height="400" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true">
</iframe>

<p>Let <code>val</code> be <span class="math inline">\(165\)</span> in the explanation below. Click to show.</p>
<p>:::{note} Explanation :class: dropdown</p>
<p>Make columns 1, 16, 256, 4096 which correspond to increasing integer powers of sixteen. These columns also correspond to a 4-digit binary number, e.g., <code>0x _ _ _ _</code>.</p>
<ol type="1">
<li>Take the largest power: <span class="math inline">\(16^3 = 4096\)</span>. This does not fit into <code>val</code>, so we set the 4th-from-the-right space to <code>0</code>, e.g., <code>0x 0 _ _ _</code>.</li>
<li>Take the next power: <span class="math inline">\(16^2 = 256\)</span>. This does not fit into <code>val</code>, so we set the 3rd-from-the-right space to <code>0</code>, e.g., <code>0x 0 0 _ _</code>.</li>
<li>Take the next power: <span class="math inline">\(16^1 = 16\)</span>. Count how many times you can “use” it; at most ten <span class="math inline">\(16\)</span>’s fit into <code>val</code>, which is currently <span class="math inline">\(165\)</span>. Ten is the hexadecimal digit <code>A</code>, so we set the 2nd-from-the-right space to <code>A</code>, e.g., <code>0x 0 0 A _</code>. Subtract <span class="math inline">\(10 \times 16^1\)</span> from <span class="math inline">\(165\)</span> and update <code>val</code> to <span class="math inline">\(5\)</span>.</li>
<li>Take the next power, which is also the smallest: <span class="math inline">\(16^0 = 1\)</span>, or one. Count how many times you can “use” it; at most five <span class="math inline">\(1\)</span>’s fit into <code>val</code>, which is currently <span class="math inline">\(5\)</span>. Se the rightmost space to <code>5</code>, e.g., <code>0x 0 0 A 5</code>. Update <code>val</code> to <span class="math inline">\(0\)</span>.</li>
</ol>
<p>The resulting hexadecimal numeral is <code>0x00A5</code>, or equivalently, <code>0xA5</code> if we dropped leading zeros.</p>
<p>You may have noticed that we included <span class="math inline">\(16^3\)</span> and <span class="math inline">\(16^2\)</span>, which are both too large for representing <span class="math inline">\(165\)</span>. This is to show you that leading zeros are alright and can be dropped once you have gotten your result.</p>
<p>:::</p>
<p>We leave it to you to translate the binary conversion process we described colloquially into a hexadecimal conversion process.</p>
</section>
<section id="binary-leftrightarrow-hexadecimal-is-straightforward" class="level3">
<h3 class="anchored" data-anchor-id="binary-leftrightarrow-hexadecimal-is-straightforward">Binary <span class="math inline">\(\leftrightarrow\)</span> Hexadecimal Is Straightforward</h3>
<p>Given the above, consider the following process for converting to binary to hexidecimal, which composes the processes we’ve discussed above:</p>
<ol type="1">
<li>Convert binary to decimal.</li>
<li>Convert decimal to hexadecimal.</li>
</ol>
<p>This process is tedious—computing powers of twos is doable, but does every computer architect memorize powers of sixteen? Instead, we can <em>directly</em> convert between binary and hexadecimal with the observation:</p>
<blockquote class="blockquote">
<p>There exists a one-to-one mapping between the set of hexadecimal digits and the set of length-four binary strings.</p>
</blockquote>
<p>The above observation implies that a <span class="math inline">\(4k\)</span>-length binary string can be translated into a <span class="math inline">\(k\)</span>-length hexadecimal string by independently converting each length-4 binary string into a hexadecimal digit, then concatenating the result. (We leave the proof of this to those of you that are enthusiastic mathematicians.) This makes conversion between binary and hexadecimal much easier:</p>
<p>To convert <code>0x1E</code> to binary:</p>
<ul>
<li><code>1</code> in hexadecimal is <code>0001</code> in binary</li>
<li><code>E</code> in hexadecimal is <code>1110</code> in binary</li>
<li>Concatenate: <code>0001 1110</code> (we include the spaces to make visualizing easier)</li>
<li>Drop leading zeros and compress spaces. (Optional) Add the <code>0b</code> prefix to denote binary: <code>0b11110</code></li>
</ul>
<p>To convert <code>0b11110</code> to hexadecimal:</p>
<ul>
<li>First group into full 4-bit strings, left-padding with zeros where necessary: <code>0001 1110</code></li>
<li><code>0001</code> in binary is <code>1</code> in hexadecimal</li>
<li><code>1110</code> in hexadecimal is <code>E</code> in hexadecimal</li>
<li>Concatenate: <code>0x1E</code> (we add the <code>0x</code> prefix to denote hexadecimal)</li>
</ul>
<div class="{tip}">
<p>Again, memorize <strong>?@tbl-dec-hex-bin-16</strong>!</p>
</div>
</section>
</section>
<section id="the-computer-knows-it-too" class="level2">
<h2 class="anchored" data-anchor-id="the-computer-knows-it-too">The computer knows it, too</h2>
<p>At this point, it’s worthwhile to remind first-time readers that the two-character prefix <code>0b</code> and <code>0x</code> denote that the digits should be interpreted as binary and hexadecimal representations, respectfully. The <code>0</code> in <code>0b</code> and <code>0x</code> doesn’t mean anything by itself.</p>
<p>These prefixes allow computers to parse strings of digits and interpret them in their intended base.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode c code-with-copy"><code class="sourceCode c"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="pp">#include </span><span class="im">&lt;stdio.h&gt;</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="dt">int</span> main<span class="op">()</span> <span class="op">{</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">const</span> <span class="dt">int</span> N <span class="op">=</span> <span class="dv">1234</span><span class="op">;</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  printf<span class="op">(</span><span class="st">"Decimal: </span><span class="sc">%d\n</span><span class="st">"</span><span class="op">,</span>N<span class="op">);</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  printf<span class="op">(</span><span class="st">"Hex:    </span><span class="sc">%x\n</span><span class="st">"</span><span class="op">,</span>N<span class="op">);</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  printf<span class="op">(</span><span class="st">"Octal:   </span><span class="sc">%o\n</span><span class="st">"</span><span class="op">,</span>N<span class="op">);</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  printf<span class="op">(</span><span class="st">"Literals (not supported by all compilers):</span><span class="sc">\n</span><span class="st">"</span><span class="op">);</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  printf<span class="op">(</span><span class="st">"0x4d2         = </span><span class="sc">%d</span><span class="st"> (hex)</span><span class="sc">\n</span><span class="st">"</span><span class="op">,</span> <span class="bn">0x4d2</span><span class="op">);</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  printf<span class="op">(</span><span class="st">"0b10011010010 = </span><span class="sc">%d</span><span class="st"> (binary)</span><span class="sc">\n</span><span class="st">"</span><span class="op">,</span> <span class="bn">0b10011010010</span><span class="op">);</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  printf<span class="op">(</span><span class="st">"02322         = </span><span class="sc">%d</span><span class="st"> (octal, prefix 0 - zero)</span><span class="sc">\n</span><span class="st">"</span><span class="op">,</span> <span class="bn">0x4d2</span><span class="op">);</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> <span class="dv">0</span><span class="op">;</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<pre><code>Decimal: 1234
Hex:     4d2
Octal:   2322
Literals (not supported by all compilers):
0x4d2         = 1234 (hex)
0b10011010010 = 1234 (binary)
02322         = 1234 (octal, prefix 0 - zero)</code></pre>
<p>We don’t expect you to understand this code at this time. We will discuss C syntax, compilers, literals, etc. very soon. We also will not cover octal literals in this course; most standard C compilers will recognize hexadecimal and binary literals.</p>
<p>(which-base)= ## Which base do we use?</p>
<p>Remember that there is only ever one number; this value that can be represented in multiple ways. The below are all representations of the same number, thirty-two:</p>
<ul>
<li><span class="math inline">\(32_{10}\)</span>, or simply <span class="math inline">\(32\)</span>. We recommend you write <span class="math inline">\(32_{ten}\)</span> if you’re writing by hand.</li>
<li><code>0x20</code>, or the hexadecimal numeral <code>20</code></li>
<li><code>0b10000</code>, or the binary numeral <code>10000</code></li>
<li><span class="math inline">\(20_{16}\)</span>. We recommend <span class="math inline">\(20_{hex}\)</span> if you’re writing by hand.</li>
<li><span class="math inline">\(10000_{2}\)</span>. We recommend <span class="math inline">\(10000_{two}\)</span> if you’re writing by hand.</li>
</ul>
<p>Different representations serve different purposes:</p>
<ul>
<li><strong>Decimal</strong>: Great for humans, especially when doing arithmetic. We hope you won’t ever forget base-10 :-)</li>
<li><strong>Binary</strong>: What computers use. To a computer, numbers are stored as binary data, regardless of how numbers are specified.</li>
<li><strong>Hex</strong>: Hopefully you have realized by now that long strings of binary numbers are hard to parse. Hexadecimal is terrible for arithmetic on paper, but it is much more compact than binary while also being much much easier than decimal as a more compact way of representing binary values.</li>
</ul>
<p>We use two strategies in this course to more easily visualize strings of 32 bits, 64 bits, etc.: * Group 4 bits at a time, e.g., <code>0b0011 1010</code> * Convert each group of 4 bits to its hexadecimal digit, e.g., <code>0x3A</code></p>
<p>Above all, remember that computers operate in binary, but humans don’t. So it’s good to get more comfortable with converting between these representations before we move further.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>