---
title: "Signed Representations"
subtitle: "UC Berkeley, CS 61C"
---

## Precheck

Unsigned binary numbers work for natural numbers, but many calculations use negative numbers as well. To deal with this, a number of different schemes have been used to represent signed numbers. Here are two common schemes:

### Two’s Complement 

(a) We can write the value of an $n$-digit two's complement number as 
$$
\sum_{i=0}^{n-2} 2^i d_i - 2^{n-1} d_{n-1}
$$
(b) Negative numbers will have a 1 as their most significant bit (MSB). Plugging in $d_{n-1} = 1$ to the formula above gets us 
$$
\sum_{i=0}^{n-2} 2^i d_i - 2^{n-1}
$$
(c) Meanwhile, positive numbers will have a 0 as their MSB. Plugging in $d_{n-1} = 0$ gets us
$$
\sum_{i=0}^{n-2} 2^i d_i
$$
which is very similar to unsigned numbers.

(d) To negate a two's complement number: flip all the bits and add 1. 
(e) Addition is exactly the same as with an unsigned number. 
(f) Only one 0, and it’s located at `0b0`. 

### Biased Representation
(a) The number line is shifted so that the smallest number we want to be representable would be `0b0...0`. 
(b) To find out what the represented number is, read the representation as if it was an unsigned number, then add the bias. 
(c) We can shift to any arbitrary bias we want to suit our needs. To represent (nearly) as much negative numbers as positive, a commonly-used bias for $N$-bits is $-(2^{N-1} - 1)$.

## Summary & Questions

You should be able to do:

* Conversion between binary, decimal, and hexademical
* Conversion with signed numbers
* Arithmetic with binary and hexadecimal numbers

### Conceputal Review Questions
1. What is a bit? How many bits are in a byte? Nibble?

::: {.callout-note title="Answer" collapse="true"}
A bit is the smallest unit of digital information and it can be either 0 of 1. There are 4 bits in a nibble and 8 bits in a byte.

See: [Lecture 2 Slide 13](https://docs.google.com/presentation/d/1dmCk2fZz-P8VedzAXnVmJiYPKszVka5NKmTuLJ6hqZc/edit?slide=id.g2af3b38b3e2_1_154#slide=id.g2af3b38b3e2_1_154)
:::

2. What is overflow?

::: {.callout-note title="Answer" collapse="true"}
When the result of an arithmetic operation is outside the range of what is representable by given number of bits.

See: [Lecture 2 Slide 26](https://docs.google.com/presentation/d/1dmCk2fZz-P8VedzAXnVmJiYPKszVka5NKmTuLJ6hqZc/edit?slide=id.g2af3b38b3e2_1_186#slide=id.g2af3b38b3e2_1_186)
:::

3. What is the range of numbers representable by $n$-bit unsigned, sign-magnitude, one's complement, two's complement, and biased notation?

::: {.callout-note title="Answer" collapse="true"} 
* **Unsigned**: $[0, 2^n-1]$
* **Sign-Magnitude**: $[-(2^{n-1} - 1), 2^{n-1} - 1]$
* **One's complement**: $[-(2^{n-1} - 1), 2^{n-1} - 1]$
* **Two's complement**: $[-2^{n-1}, 2^{n-1} - 1]$
* **Bias**: $[0+$bias$, 2^n-1+$bias$]$

See:  [Lecture 2](https://docs.google.com/presentation/d/1dmCk2fZz-P8VedzAXnVmJiYPKszVka5NKmTuLJ6hqZc/edit?slide=id.g32e4dda2ba9_0_123#slide=id.g32e4dda2ba9_0_123)
:::

4. How many ways to represent zero do these representations have, $n$-bit unsigned, sign-magnitude, one's complement, two's complement, and biased notation?

::: {.callout-note title="Answer" collapse="true"}
* **Unsigned**: 1
* **Sign-Magnitude**: 2
* **One's complement**: 2
* **Two's complement**: 1
* **Bias**: 1 or 0 (depending on bias)

See: [Lecture 2](https://docs.google.com/presentation/d/1dmCk2fZz-P8VedzAXnVmJiYPKszVka5NKmTuLJ6hqZc/edit?slide=id.g32e4dda2ba9_0_123#slide=id.g32e4dda2ba9_0_123)
:::


